package l1.rngtoolkit.generators;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

import l1.rngtoolkit.configs.GeneratorConfig;
import l1.rngtoolkit.models.Range;

public class ByteGeneratorTest {

  @Test
  public void testGenerateRandomIntegerInRange() {
    GeneratorConfig config = new GeneratorConfig();
    config.setSeed(62378L);
    ByteGenerator generator = new ByteGenerator(config);
    Range<Byte> range = new Range<>((byte) 1, (byte) 10);
    byte randomByte = generator.generateRandomByteInRange(range);
    assertTrue(randomByte >= 1 && randomByte <= 10, "Generated byte is within the specified range.");
  }
}
